version = 0.1
[default.deploy.parameters]
stack_name = "nofraud"
resolve_s3 = true
s3_prefix = "nofraud"
region = "us-west-2"
profile = "production_apps"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "NodeEnv=\"production\" ApiDomainName=\"nofraud-api.tinygrape.co\" HostedZoneId=\"Z02602473SGG82Z7HSD92\" C7ApiUrl=\"https://api.commerce7.com\" C7AppId=\"nofraud\" C7AppSecret=\"Mi7hnfoVFLvo2wxjk6pfs4eWeMkodPrJ7n9FLyKammsjBvhxPu28JLoHbwEstCoM\" SendGridApiKey=\"todo\""
