version = 0.1
[default.deploy.parameters]
stack_name = "nofraud"
resolve_s3 = true
s3_prefix = "nofraud"
region = "us-west-2"
profile = "production_apps"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
