AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda APP
Globals:
  Api:
    BinaryMediaTypes:
      - '*~1*'

Resources:
  APP:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.app
      Runtime: nodejs20.x
      Timeout: 180
      MemorySize: 512
      CodeUri: ./
      ReservedConcurrentExecutions: 100
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !GetAtt TriggerQueue.Arn
            BatchSize: 1
        API:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          NODE_ENV: production
          # C7_API_PASSWORD: '{{resolve:ssm:/lambdas/shipcompliant/c7_api_password:1}}'
          # C7_API_USERNAME: '{{resolve:ssm:/lambdas/shipcompliant/c7_api_username:1}}'

  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: node-modules
      Description: Node Modules for Lambda Apps
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs20.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Delete
