AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda APP
Globals:
  Api:
    BinaryMediaTypes:
      - '*~1*'
Parameters:
  ApiDomainName:
    Description: API Domain name to use for this APP.
    Type: String
  HostedZoneId:
    Description: Route53 Domain Hosted ZoneId
    Type: String

Resources:
  APP:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.app
      Runtime: nodejs20.x
      Timeout: 180
      MemorySize: 512
      CodeUri: ./
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaFunctionSecurityGroup
        SubnetIds:
          - !ImportValue 'app-shared-infrastructure:PublicSubnetOne'
          - !ImportValue 'app-shared-infrastructure:PublicSubnetTwo'
      Layers:
        - !Ref NodeModulesLayer
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !GetAtt SqsQueue.Arn
            BatchSize: 1
        API:
          Type: Api
          Properties:
            Path: /beta/{proxy+}
            Method: any
      Environment:
        Variables:
          NODE_ENV: production
          # C7_API_PASSWORD: '{{resolve:ssm:/lambdas/shipcompliant/c7_api_password:1}}'
          # C7_API_USERNAME: '{{resolve:ssm:/lambdas/shipcompliant/c7_api_username:1}}'

  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-sqs-queue'
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - 'DeadLetterQueue'
            - 'Arn'
        maxReceiveCount: 3
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-sqs-deadletter-queue'

  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: node-modules
      Description: Node Modules for Lambda Apps
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs20.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Delete

  LambdaFunctionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the Lambda containers
      VpcId: !ImportValue 'app-shared-infrastructure:VPCId'
  RdsSecurityGroupIngressFromLambda:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from lambda function
      GroupId: !ImportValue 'app-shared-infrastructure:RdsSecurityGroup'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref 'LambdaFunctionSecurityGroup'

  Domain:
    DomainName: tinygrape.co
    CertificateArn: !ImportValue 'app-shared-infrastructure:CertificateDomainName'
    EndpointConfiguration: REGIONAL
    Route53:
      HostedZoneId: !Ref HostedZoneId
    BasePath:
      - beta
